#! /usr/bin/env python

import itertools

def myjoin(d, array, mapfunc):
    rs = []
    for a in array:
        if mapfunc(a) not in ['?']: rs.append(mapfunc(a))
    return d.join(rs)

def my_par_join(d, array):
    rss = []
    for a in array:
        if a.altword != a.word and a.altword != None:
            rss.append([a.word, a.altword])
        else:
            rss.append([a.word])

    for i in itertools.product(*rss):
        rs = []
        for a in i:
            if a not in ['?', '']:
                rs.append(a)
        yield d.join(rs)
    #return d.join(rss)


dict_stages = {
"Pennsylavanian":1,
###appear in paleodb as stages
"Aalenian":1,
"Abereiddian":1,
"Actonian":1,
"Adavere":1,
"Adorf":1,
"Aegean":1,
"Aeronian":1,
"Aksayan":1,
"Alaunian":1,
"Albian":1,
"Alexandrian":1,
"Alportian":1,
"Altonian":1,
"Aluoja":1,
"Amgan":1,
"Angulata":1,
"Anisian":1,
"Aptian":1,
"Aquilan":1,
"Aquitanian":1,
"Aratauran":1,
"Arcadian":1,
"Arenig":1,
"Arenigian":1,
"Arikareean":1,
"Arnsbergian":1,
"Arowhanan":1,
"Arshantan":1,
"Artinskian":1,
"Arundian":1,
"Asbian":1,
"Aseri":1,
"Ashbyan":1,
"Ashgill":1,
"Ashgillian":1,
"Asselian":1,
"Astaracian":1,
"Atdabanian":1,
"Atokan":1,
"Aurelucian":1,
"Autunian":1,
"Ayusokkanian":1,
"Badenian":1,
"Bajocian":1,
"Baodean":1,
"Barremian":1,
"Barstovian":1,
"Bartonian":1,
"Bashkirian":1,
"Bathonian":1,
"Batyrbaian":1,
"Bendigonian":1,
"Berounian":1,
"Berriasian":1,
"Bifrons":1,
"Billingen":1,
"Bithynian":1,
"Black River":1,
"Blackhillsian":1,
"Blackriveran":1,
"Blancan":1,
"Bohdalec":1,
"Bolindian":1,
"Bolorian":1,
"Boomerangian":1,
"Bortonian":1,
"Botomian":1,
"Branchian":1,
"Bridgerian":1,
"Brigantian":1,
"Bucklandi":1,
"Bumbanian":1,
"Buntsandstein":1,
"Burdigalian":1,
"Burrellian":1,
"Burtsevian":1,
"Caerfai":1,
"Calabrian":1,
"Callovian":1,
"Cambrian":1,
"Campanian":1,
"Canadian":1,
"Cantabrian":1,
"Capitan":1,
"Capitanian":1,
"Caradoc":1,
"Caradocian":1,
"Carboniferous":1,
"Carlottense":1,
"Carnian":1,
"Casamayoran":1,
"Cassinian":1,
"Castlecliffian":1,
"Castlemainian":1,
"Cautleyan":1,
"Cayugan":1,
"Cazenovia":1,
"Cenomanian":1,
"Cenozoic":1,
"Cf1":1,
"Cf2":1,
"Cf3":1,
"Chadian":1,
"Chadronian":1,
"Changhsingian":1,
"Chapadmalalan":1,
"Chasicoan":1,
"Chatfieldian":1,
"Chattian":1,
"Chazy":1,
"Chazyan":1,
"Cheneyan":1,
"Chesterian":1,
"Chewtonian":1,
"Chokierian":1,
"Cincinnatian":1,
"Cisuralian":1,
"Clarendonian":1,
"Clarkforkian":1,
"Clifdenian":1,
"Clinton":1,
"Colhuehuapian":1,
"Colloncuran":1,
"Concavum":1,
"Coniacian":1,
"Costonian":1,
"Couvinien":1,
"Cressagian":1,
"Cretaceous":1,
"Cryogenian":1,
"Daleje":1,
"Danian":1,
"Dapingian":1,
"Darriwilian":1,
"Datsonian":1,
"Davoei":1,
"Dawan":1,
"Delamaran":1,
"Deming":1,
"Demingian":1,
"Deseadan":1,
"Desmoinesian":1,
"Devonian":1,
"Dienerian":1,
"Discites":1,
"Divisaderan":1,
"Dobrotiva":1,
"Dobrotivian":1,
"Dolgellian":1,
"Dorogovilovian":1,
"Dresbachian":1,
"Duchesnean":1,
"Duntroonian":1,
"Duyunian":1,
"Dyeran":1,
"Eastonian":1,
"Edenian":1,
"Ediacaran":1,
"Edmontonian":1,
"Eifel":1,
"Eifelian":1,
"Elton":1,
"Ems":1,
"Emsian":1,
"Ensenadan":1,
"Ensyan":1,
"Eocene":1,
"Ergilian":1,
"Falciferum":1,
"Famennian":1,
"Fassanian":1,
"Fennian":1,
"Floian":1,
"Floran":1,
"Franconian":1,
"Franklinian":1,
"Frasnian":1,
"Freboldi":1,
"Friasian":1,
"Furongian":1,
"Gallic":1,
"Gamachian":1,
"Gasconadian":1,
"Gashatan":1,
"Gedinne":1,
"Gedinnine":1,
"Gelasian":1,
"Geringian":1,
"Gisbornian":1,
"Givet":1,
"Givetian":1,
"Gleedonian":1,
"Gorstian":1,
"Graybullian":1,
"Griesbachian":1,
"Guadalupian":1,
"Guzhangian":1,
"Gzhelian":1,
"Haljala":1,
"Harju":1,
"Harnagian":1,
"Harrisonian":1,
"Hastarian":1,
"Haumurian":1,
"Hauterivian":1,
"Helderberg":1,
"Hemingfordian":1,
"Hemphillian":1,
"Heretaungan":1,
"Heterian":1,
"Hettangian":1,
"Hirnantian":1,
"Holkerian":1,
"Holocene":1,
"Homerian":1,
"Houldjinian":1,
"Huayquerian":1,
"Hulo":1,
"Humphresianum":1,
"Hunderum":1,
"Ibex":1,
"Ibexian":1,
"Idamean":1,
"Idavere":1,
"Illyrian":1,
"Imlayi":1,
"Induan":1,
"Irdinmanhan":1,
"Irenian":1,
"Irginian":1,
"Irvingtonian":1,
"Itaboraian":1,
"Iverian":1,
"Ivorian":1,
"Jaagarahu":1,
"Jamesoni":1,
"Jefferson":1,
"Jeffersonian":1,
"Jiusian":1,
"Johvi":1,
"Judithian":1,
"Julian":1,
"Jurassic":1,
"Juuru":1,
"Kaiatan":1,
"Kaihikuan":1,
"Kanense":1,
"Kapitean":1,
"Kashirian":1,
"Kasimovian":1,
"Katian":1,
"Kazanian":1,
"Keila":1,
"Ketyan":1,
"Khamovnichean":1,
"Kimmeridgian":1,
"Kinderhookian":1,
"Kinderscoutian":1,
"Kirkfieldian":1,
"Klabava":1,
"Korangan":1,
"Kosovian":1,
"Kralodvorian":1,
"Kubergandian":1,
"Kukruse":1,
"Kunae":1,
"Kunda":1,
"Kungurian":1,
"Kupferschiefer":1,
"Kuressaare":1,
"Kuzel":1,
"Lacian":1,
"Ladinian":1,
"Laeviuscula":1,
"Lancefieldian":1,
"Lancian":1,
"Langhian":1,
"Lasnamagi":1,
"Laventan":1,
"Leine":1,
"Leintwardine":1,
"Lenian":1,
"Leonard":1,
"Letna":1,
"Levesquei":1,
"Liasicus":1,
"Liben":1,
"Lillburnian":1,
"Llandeilian":1,
"Llandeilo":1,
"Llandovery":1,
"Llanvirn":1,
"Llanvirnian":1,
"Lochkovian":1,
"Longobardian":1,
"Longtanian":1,
"Longvillian":1,
"Lopingian":1,
"Lostcabinian":1,
"Ludfordian":1,
"Ludlow":1,
"Lujanian":1,
"Lutetian":1,
"Lysitean":1,
"MN 1":1,
"MN 10":1,
"MN 11":1,
"MN 12":1,
"MN 13":1,
"MN 14":1,
"MN 15":1,
"MN 16":1,
"MN 17":1,
"MN 2":1,
"MN 3":1,
"MN 4":1,
"MN 5":1,
"MN 6":1,
"MN 7 + 8":1,
"MN 9":1,
"MP 10":1,
"MP 11":1,
"MP 12":1,
"MP 13":1,
"MP 14":1,
"MP 15":1,
"MP 16":1,
"MP 17A":1,
"MP 17B":1,
"MP 18":1,
"MP 19":1,
"MP 20":1,
"MP 21":1,
"MP 22":1,
"MP 23":1,
"MP 24":1,
"MP 25":1,
"MP 26":1,
"MP 27":1,
"MP 28":1,
"MP 29":1,
"MP 30":1,
"MP 6":1,
"MP 8 + 9":1,
"Maastrichtian":1,
"Maduan":1,
"Maentwrogian":1,
"Mangaorapan":1,
"Mangaotanean":1,
"Mangapanian":1,
"Mansian":1,
"Manykaian":1,
"Margaritatus":1,
"Marjumian":1,
"Marmor":1,
"Marsdenian":1,
"Marshbrookian":1,
"Mayan":1,
"Mayoan":1,
"Maysville":1,
"Maysvillian":1,
"Meishucunian":1,
"Melekesian":1,
"Melekhovian":1,
"Menevian":1,
"Meramecian":1,
"Merioneth":1,
"Mesozoic":1,
"Messinian":1,
"Migneintian":1,
"Millardan":1,
"Mindyallan":1,
"Miocene":1,
"Mississippian":1,
"Missourian":1,
"Mohawkian":1,
"Monroecreekian":1,
"Montehermosan":1,
"Montezuman":1,
"Moridunian":1,
"Morrowan":1,
"Moscovian":1,
"Motuan":1,
"Murchisonae":1,
"Murgabian":1,
"Mustersan":1,
"Myachkovian":1,
"Nabala":1,
"Nammalian":1,
"Namurian":1,
"Nangaoian":1,
"Nemakit-Daldynian":1,
"Neocomian":1,
"Neogene":1,
"Neoproterozoic":1,
"Nganasanian":1,
"Ngaterian":1,
"Niagaran":1,
"Ningkuo":1,
"Niuchehean":1,
"Noginian":1,
"Norian":1,
"Nukumaruan":1,
"Oandu":1,
"Obtusum":1,
"Ohauan":1,
"Ohesaare":1,
"Olenekian":1,
"Oligocene":1,
"Onnian":1,
"Ontarian":1,
"Opalinum":1,
"Opoitian":1,
"Ordian":1,
"Ordovician":1,
"Orellan":1,
"Oretanian":1,
"Oretian":1,
"Orleanian":1,
"Osagean":1,
"Otaian":1,
"Otamitan":1,
"Otapirian":1,
"Oxfordian":1,
"Oxynotum":1,
"Paadla":1,
"Paibian":1,
"Paleocene":1,
"Paleogene":1,
"Paleozoic":1,
"Pannonian":1,
"Parkinsoni":1,
"Pavlovoposadian":1,
"Payntonian":1,
"Peligran":1,
"Pelsonian":1,
"Pendleian":1,
"Pennsylvanian":1,
"Permian":1,
"Piacenzian":1,
"Pirgu":1,
"Piripauan":1,
"Placentian":1,
"Planorbis":1,
"Planulata":1,
"Pleistocene":1,
"Pliensbachian":1,
"Pliocene":1,
"Podolskian":1,
"Porkuni":1,
"Poundian":1,
"Pragian":1,
"Priabonian":1,
"Pridoli":1,
"Pu1":1,
"Pu3":1,
"Puaroan":1,
"Puercan":1,
"Pusgillian":1,
"Quaternary":1,
"Raikkula":1,
"Rakvere":1,
"Rancholabrean":1,
"Rangerian":1,
"Raricostatum":1,
"Rawtheyan":1,
"Rhaetian":1,
"Rhuddanian":1,
"Richmond":1,
"Richmondian":1,
"Riochican":1,
"Riphean":1,
"Roadian":1,
"Rockland":1,
"Rocklandian":1,
"Rootsikula":1,
"Rotliegendes":1,
"Runangan":1,
"Rupelian":1,
"Rusavkian":1,
"Ruscinian":1,
"Sakian":1,
"Sakmarian":1,
"Sandbian":1,
"Sandcouleean":1,
"Santacrucian":1,
"Santonian":1,
"Saranian":1,
"Sarginian":1,
"Sarka":1,
"Sarmatian":1,
"Sauzei":1,
"Selandian":1,
"Semicostatum":1,
"Senonian":1,
"Serpukhovian":1,
"Serravallian":1,
"Sevatian":1,
"Severodvinian":1,
"Sharamurunian":1,
"Sheinwoodian":1,
"Shermanian":1,
"Shikhanian":1,
"Siegen":1,
"Silurian":1,
"Sinemurian":1,
"Skullrockian":1,
"Smithian":1,
"Solvan":1,
"Soudleyan":1,
"Southwood":1,
"Spathian":1,
"Spinatum":1,
"St Davids":1,
"Stairsian":1,
"Stephanian A":1,
"Stephanian B":1,
"Stephanian C":1,
"Stephanian":1,
"Steptoean":1,
"Sterlitamakian":1,
"Sunwaptan":1,
"Taghanic":1,
"Taijangian":1,
"Taoyuanian":1,
"Tarantian":1,
"Tastubian":1,
"Tatarian":1,
"Tavgian":1,
"Telychian":1,
"Temaikan":1,
"Templetonian":1,
"Tenuicostatum":1,
"Teratan":1,
"Tertiary":1,
"Teurian":1,
"Thanetian":1,
"Thouarsense":1,
"Ti1":1,
"Ti3":1,
"Ti5":1,
"Tiffanian":1,
"Tithonian":1,
"Tiupampan":1,
"To2":1,
"To3":1,
"Toarcian":1,
"Tommotian":1,
"Tongaporutuan":1,
"Torrejonian":1,
"Tortonian":1,
"Tournaisian":1,
"Toyonian":1,
"Tremadoc":1,
"Tremadocian":1,
"Trempealeauan":1,
"Trentonian":1,
"Triassic":1,
"Tulean":1,
"Turinian":1,
"Turolian":1,
"Turonian":1,
"Tuvalian":1,
"Tyesaian":1,
"Ufimian":1,
"Uhaku":1,
"Uintan":1,
"Ulangochuian":1,
"Undillan":1,
"Uquian":1,
"Ururoan":1,
"Urutawan":1,
"Urzhumian":1,
"Valanginian":1,
"Valaste":1,
"Vallesian":1,
"Variabilis":1,
"Vendian":1,
"Vereian":1,
"Villanyian":1,
"Vinice":1,
"Virgilian":1,
"Visean":1,
"Volkhov":1,
"Volkhovian":1,
"Vormsi":1,
"Vyatkian":1,
"Waiauan":1,
"Waipawan":1,
"Waipipian":1,
"Waitakian":1,
"Wangcunian":1,
"Warendian":1,
"Warepan":1,
"Wasatchian":1,
"Waucoban":1,
"Wenlock":1,
"Westphalian A":1,
"Westphalian B":1,
"Westphalian C":1,
"Westphalian D":1,
"Westphalian":1,
"Whaingaroan":1,
"Whitcliffe":1,
"Whiteavesi":1,
"Whiterock":1,
"Whiterockian":1,
"Whitlandian":1,
"Whitneyan":1,
"Whitwellian":1,
"Wildernessian":1,
"Wolfcamp":1,
"Wonokan":1,
"Word":1,
"Wordian":1,
"Wuchiapingian":1,
"Wufeng":1,
"Yapeenian":1,
"Yarengian":1,
"Yeadonian":1,
"Ypresian":1,
"Yurakian":1,
"Zahorany":1,
"Zanclean":1,
"Zechstein":1,
"Zhanarykian":1,
"Zlichovian":1,
"early Ordovician":1,
"early Ordovician":1,
"late Ordovician":1,
"middle Ordovician":1,
########
"Lower Cretaceous":1,
"Upper Cretaceous":1
}
